green_taxi_data:
  user: root # 'user name for postgres'
  password: root # 'password for postgres'
  host: localhost # 'host for postgres'
  port: 5432 # 'port for postgres'
  db: ny_taxi # 'database name for postgres'
  table_name: taxi_data # 'name of the table where we will write the results to'
  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz # 'url of the csv file'
zone_lookup_data:
  user: root # 'user name for postgres'
  password: root # 'password for postgres'
  host: localhost # 'host for postgres'
  port: 5432 # 'port for postgres'
  db: ny_taxi # 'database name for postgres'
  table_name: lookup_data # 'name of the table where we will write the results to'
  url: https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv # 'url of the csv file'