#green_taxi_data:
#  user: root # 'user name for postgres'
#  password: root # 'password for postgres'
#  host: localhost # 'host for postgres'
#  port: 5432 # 'port for postgres'
#  db: ny_taxi # 'database name for postgres'
#  table_name: taxi_data # 'name of the table where we will write the results to'
#  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz # 'url of the csv file'
#zone_lookup_data:
#  user: root # 'user name for postgres'
#  password: root # 'password for postgres'
#  host: localhost # 'host for postgres'
#  port: 5432 # 'port for postgres'
#  db: ny_taxi # 'database name for postgres'
#  table_name: lookup_data # 'name of the table where we will write the results to'
#  url: https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv # 'url of the csv file'
green_taxi_data_jan2020:
  user: root # 'user name for postgres'
  password: root # 'password for postgres'
  host: localhost # 'host for postgres'
  port: 5432 # 'port for postgres'
  db: ny_taxi # 'database name for postgres'
  table_name: green_taxi_data # 'name of the table where we will write the results to'
  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-01.csv.gz # 'url of the csv file'
#green_taxi_data_nov2020:
#  user: root # 'user name for postgres'
#  password: root # 'password for postgres'
#  host: localhost # 'host for postgres'
#  port: 5432 # 'port for postgres'
#  db: ny_taxi # 'database name for postgres'
#  table_name: green_taxi_data # 'name of the table where we will write the results to'
#  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-11.csv.gz # 'url of the csv file'
#yellow_taxi_data_feb2019:
#  user: root # 'user name for postgres'
#  password: root # 'password for postgres'
#  host: localhost # 'host for postgres'
#  port: 5432 # 'port for postgres'
#  db: ny_taxi # 'database name for postgres'
#  table_name: yellow_taxi_data # 'name of the table where we will write the results to'
#  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-02.csv.gz # 'url of the csv file'
#yellow_taxi_data_nov20202:
#  user: root # 'user name for postgres'
#  password: root # 'password for postgres'
#  host: localhost # 'host for postgres'
#  port: 5432 # 'port for postgres'
#  db: ny_taxi # 'database name for postgres'
#  table_name: yellow_taxi_data # 'name of the table where we will write the results to'
#  url: https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-03.csv.gz # 'url of the csv file'
